---
title: "Data Wrangling"
author: "Maeve Gualtieri-Reed"
date: "2026-03-29"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Setup
```{r}
library(here)
library(readxl)
library(dplyr)
library(tidyverse)
library(forecast)
library(cowplot)
```


# Load in data set

## load
```{r}
load_full <- read_excel("load.xlsx") %>% 
  mutate(daily = rowMeans(across(3:26), na.rm = TRUE)) %>% 
  mutate(date = ymd(date)) %>% 
  select(date,daily)

load_train <- load_full %>% 
  filter(date < as.Date("2010-07-01"))

```
## temp and humidity

```{r}
#all temp
temp <- read_excel("temperature.xlsx") %>% 
  mutate(hourly = rowMeans(across(3:30))) %>% 
  select(date,hr,hourly) %>% 
  pivot_wider(names_from = hr,
              values_from = hourly) %>% 
  mutate(avg_temp = rowMeans(across(2:25))) %>% 
  select(date,avg_temp)

#train temp
temp_train <- temp  %>% 
  filter(date < as.Date("2010-07-01"))

write_csv(temp, 'data/temp_processed.csv')
write.csv(temp_train, "data/temp_train.csv")

#all humidity
humidity <- read_excel("relative_humidity.xlsx") %>% 
  mutate(hourly = rowMeans(across(3:30))) %>% 
  select(date,hr,hourly) %>% 
  pivot_wider(names_from = hr,
              values_from = hourly) %>% 
  mutate(avg_humidity = rowMeans(across(2:25))) %>% 
  select(date,avg_humidity)

#train humidity
humidity_train <- humidity %>% 
  filter(date < as.Date("2010-07-01"))

write_csv(humidity, 'data/humidity_processed.csv')
write.csv(humidity_train, "data/humidity_train.csv")
  
```

## check for missing data

```{r}
summary(load_full$daily) #no NA

check_nobs <- length(seq.Date(
  from = as.Date("2005-01-01"),
  to   = as.Date("2011-06-30"),
  by   = "day"
))

nobs <- nrow(load)
#number of expected observations = number of actual observations no missing data
```

## Create time series object

```{r}
ts_load_full <- msts(load_full$daily, 
                seasonal.periods =c(7,365.25), #7 = weekly, 365.25 = yearly 
                start=c(2005,1,1))

ts_load_train <- msts(load_train$daily, 
                seasonal.periods =c(7,365.25), #7 = weekly, 365.25 = yearly 
                start=c(2005,1,1))
```

#Examine data

```{r}
autoplot(ts_load_full)
autoplot(ts_load_train)

ts_load_full %>% mstl() %>%
  autoplot()
```

