---
title: "Final Report"
author: "Maeve Gualtieri-Reed, Sadie Kasten, Leo Zhang"
date: "2026-04-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=F}
library(here)
library(readxl)
library(dplyr)
library(tidyverse)
library(forecast)
library(cowplot)
library(smooth)
library(writexl)
```

#Introduction


#Methods



#Analysis
```{r, include=F}
load <- read_excel("load.xlsx") %>% 
  mutate(daily = rowMeans(across(3:26), na.rm = TRUE)) %>% 
  mutate(date = ymd(date)) %>% 
  select(date,daily)
```

```{r, include=F}
msts_load <- msts(load$daily, 
                seasonal.periods =c(7,365.25), #7 = weekly, 365.25 = yearly 
                start=c(2005,1,1))
```

The first of the five top models that performed well against the actual data for July 2011 was created using the TBATS forecasting model. This model was trained using the simply the load data and forecast for the month of July. The MAPE score of this forecasting model was XXXX.
The results are plotted below.
```{r}
#TBATS for for load no training
TBATS_model <- tbats(msts_load)

TBATS_forecast <- forecast(TBATS_model, h=31)

plot(TBATS_forecast)
```




#Conclusions
