---
title: "Maeve"
author: "Maeve Gualtieri-Reed"
date: "2026-03-31"
output: pdf_document
---


```{r}
library(here)
library(readxl)
library(dplyr)
library(tidyverse)
library(forecast)
library(cowplot)
library(writexl)
```



# Load in data set

```{r}
load_full <- read_excel("Downloads/load.xlsx") %>% 
  mutate(daily = rowMeans(across(3:26), na.rm = TRUE)) %>% 
  mutate(date = ymd(date)) %>% 
  select(date,daily)

#load_full <- read_excel("load.xlsx") %>% 
 # mutate(daily = rowMeans(across(3:26), na.rm = TRUE)) %>% 
 # mutate(date = ymd(date)) %>% 
 # select(date,daily)

load_train <- load_full %>% 
  filter(date < as.Date("2010-07-01"))

load_test <- load_full %>% 
  filter(date >= as.Date("2010-07-01")) %>% 
  filter(date <= as.Date("2010-07-31"))

temp_full <- read.csv("Downloads/temp_processed.csv")
temp_train<- temp_full %>% 
  filter(date < as.Date("2010-07-01"))
temp_test <- temp_full %>% 
  filter(date >= as.Date("2010-07-01")) %>% 
  filter(date <= as.Date("2010-07-31"))

humidity_full <- read.csv("Downloads/humidity_processed.csv")
humidity_train<- humidity_full %>% 
  filter(date < as.Date("2010-07-01"))
humidity_test <- humidity_full %>% 
  filter(date >= as.Date("2010-07-01")) %>% 
  filter(date <= as.Date("2010-07-31"))

#temp_full <- read.csv("data/temp_processed.csv")
#humidity_full <- read.csv("data/humidity_processed.csv")
```

# Create time series object

```{r}
ts_load_full <- msts(load_full$daily, 
                seasonal.periods =c(7,365.25), #7 = weekly, 365.25 = yearly 
                start=c(2005,1,1))

ts_load_train <- msts(load_train$daily, 
                seasonal.periods =c(7,365.25), #7 = weekly, 365.25 = yearly 
                start=c(2005,1,1))

ts_load_test <- subset(ts_load_full, start = length(ts_load_full)- 364,
                       end = length(ts_load_full)-334)

ts_temp_full<- msts(temp_full$avg_temp, 
                seasonal.periods =c(7,365.25), #7 = weekly, 365.25 = yearly 
                start=c(2005,1,1))

ts_humid_full <- msts(humidity_full$avg_humidity, 
                seasonal.periods =c(7,365.25), #7 = weekly, 365.25 = yearly 
                start=c(2005,1,1))
```

# Examine data

```{r}
autoplot(ts_load_full)
autoplot(ts_load_train)
```

# Models

## ARIMA + fourier
### ARIMA 212
```{r}
ARIMA_212 <- auto.arima(ts_load_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_train, 
                                          K=c(2,12))
                             )

#Forecast with ARIMA fit
#also need to specify h for fourier terms
ARIMA_212_forecast <- forecast(ARIMA_212,
                           xreg=fourier(ts_load_train,
                                        K=c(2,12),
                                        h=31),
                           h=31
                           ) 

ARIMA_212_scores <- accuracy(ARIMA_212_forecast$mean, ts_load_test)

ARIMA_212_data<- data.frame(
  date = seq(as.Date("2011-07-01"), length.out = 31, by = "day"),
  value = ARIMA_212_forecast$mean
)

write_csv(ARIMA_212_data, 'Submissions/ARIMAfour1.csv')
```

### Exog111: k = 1,11; include temp and humidity
Chatgpt used to understand how to include temp and humidity along with fourier in xreg

```{r}
fourier_terms <- fourier(ts_load_full, K=c(3,8))
xreg_data <- left_join(temp_full, humidity_full, by = "date") %>% 
  head(-1) %>% 
  select(avg_temp, avg_humidity) %>% 
  cbind(fourier_terms) %>% 
  as.matrix()


ARIMA_exog38 <- auto.arima(ts_load_full, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=xreg_data
                             )

ARIMA_temp <- auto.arima(ts_temp_full, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_temp_full, 
                                          K=c(2,12))
                             )

ARIMA_humid <- auto.arima(ts_humid_full, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_humid_full, 
                                          K=c(2,12))
                             )

ARIMA_temp_forecast <- forecast(ARIMA_temp,
                           xreg=fourier(ts_temp_full, 
                                           K=c(2,12),
                                        h=31),
                           h=31
                             )

ARIMA_humid_forecast <- forecast(ARIMA_humid,
                           xreg=fourier(ts_humid_full, 
                                           K=c(2,12),
                                        h=31),
                           h=31
                             )

temp_forecast <- data.frame(avg_temp = ARIMA_temp_forecast$mean)
humid_forecast <- data.frame(avg_humidity = ARIMA_humid_forecast$mean)

fourier_terms_forecast <- fourier(ts_load_full, K=c(3,8), h= 31)
xreg_data_forecast <- cbind(temp_forecast,humid_forecast,fourier_terms_forecast) %>% 
  as.matrix()


ARIMA_exog38_forecast <- forecast(ARIMA_exog38,
                           xreg=xreg_data_forecast,
                           h=31
                           ) 

ARIMA_exog38_data<- data.frame(
  date = seq(as.Date("2011-07-01"), length.out = 31, by = "day"),
  value = ARIMA_exog38_forecast$mean
)

write_csv(ARIMA_exog38_data, 'ARIMA_exog38_data.csv')
```
### exog w tbat forecast
```{r}
fourier_terms <- fourier(ts_load_full, K=c(3,8))
xreg_data <- left_join(temp_full, humidity_full, by = "date") %>% 
  head(-1) %>% 
  select(avg_temp, avg_humidity) %>% 
  cbind(fourier_terms) %>% 
  as.matrix()


ARIMA_exog38 <- auto.arima(ts_load_full, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=xreg_data
                             )
temp_clean <- na.interp(temp_full$avg_temp)
temp_tbats <- tbats(temp_clean)
temp_tbats_forecast <- forecast(temp_tbats, h = 31)

humid_clean <- na.interp(humidity_full$avg_humidity)
humid_tbats <- tbats(humid_clean)
humid_tbats_forecast <- forecast(humid_tbats, h = 31)

temp_forecast <- data.frame(avg_temp = temp_tbats_forecast$mean)
humid_forecast <- data.frame(avg_humidity = humid_tbats_forecast$mean)

fourier_terms_forecast <- fourier(ts_load_full, K=c(3,8), h= 31)
xreg_data_forecast <- cbind(temp_forecast,humid_forecast,fourier_terms_forecast) %>% 
  as.matrix()


ARIMA_exog38_forecast <- forecast(ARIMA_exog38,
                           xreg=xreg_data_forecast,
                           h=31
                           ) 

ARIMA_exog38tbats_data<- data.frame(
  date = seq(as.Date("2011-07-01"), length.out = 31, by = "day"),
  value = ARIMA_exog38_forecast$mean
)

write_csv(ARIMA_exog38tbats_data, 'ARIMA_exog38tbats_data.csv')
```
### Run a lop for exog

```{r}

temp_clean <- na.interp(temp_train$avg_temp)
temp_clean_df <- data.frame(avg_temp = temp_clean)
temp_tbats <- tbats(temp_clean)
temp_tbats_forecast <- forecast(temp_tbats, h = 31)


humid_clean <- na.interp(humidity_train$avg_humidity)
humid_clean_df <- data.frame(avg_humidity = humid_clean)
humid_tbats <- tbats(humid_clean)
humid_tbats_forecast <- avg_humidity=forecast(humid_tbats, h = 31)


temp_forecast <- data.frame(avg_temp = temp_tbats_forecast$mean)
humid_forecast <- data.frame(avg_humidity = humid_tbats_forecast$mean)

results <- data.frame()
for (k1 in 1:2) {
  for (k2 in 8:9) {
    xreg_fit <- cbind(temp_clean_df,humid_clean_df,
                                   fourier(ts_load_train, K = c(k1,k2))) %>% 
      as.matrix()
    fit <- auto.arima(ts_load_train,
                      xreg = xreg_fit,
                      seasonal = FALSE)
    xreg_forecast <- cbind(temp_forecast, humid_forecast, fourier(ts_load_train,
                                        K=c(k1,k2),
                                        h=31)) %>% 
      as.matrix()
    forecast <- forecast(fit,
                           xreg=xreg_forecast,
                           h=31
                           ) 
    scores<- accuracy(forecast$mean, ts_load_test)
    results <- rbind(results,
                     data.frame(K1=k1, K2=k2, scores))
  }
}
```


### Run a loop for no exog

```{r}
results <- data.frame()
for (k1 in 1:3) {
  for (k2 in 8:15) {
    fit <- auto.arima(ts_load_train,
                      xreg = fourier(ts_load_train, K = c(k1, k2)),
                      seasonal = FALSE)
    forecast <- forecast(fit,
                           xreg=fourier(ts_load_train,
                                        K=c(k1,k2),
                                        h=31),
                           h=31
                           ) 
    scores<- accuracy(forecast$mean, ts_load_test)
    results <- rbind(results,
                     data.frame(K1=k1, K2=k2, scores))
  }
}
```


### Top 4 model AIC

```{r}

ARIMA_110 <- auto.arima(ts_load_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_train, 
                                          K=c(1,10))
                             )

ARIMA_18 <- auto.arima(ts_load_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_train, 
                                          K=c(1,8))
                             )

ARIMA_111 <- auto.arima(ts_load_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_train, 
                                          K=c(1,11))
                             )

ARIMA_310 <- auto.arima(ts_load_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_train, 
                                          K=c(3,10))
                             )

ARIMA_38 <- auto.arima(ts_load_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_train, 
                                          K=c(3,8))
                             )

ARIMA_311 <- auto.arima(ts_load_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_train, 
                                          K=c(3,11))
                             )


AIC <- data.frame() %>% 
  rbind(data.frame(Model=110, AIC = AIC(ARIMA_110))) %>% 
  rbind(data.frame(Model=18, AIC = AIC(ARIMA_18))) %>% 
  rbind(data.frame(Model=111, AIC = AIC(ARIMA_111))) %>% 
  rbind(data.frame(Model=310, AIC = AIC(ARIMA_310))) %>% 
  rbind(data.frame(Model=38, AIC = AIC(ARIMA_38))) %>% 
  rbind(data.frame(Model=311, AIC = AIC(ARIMA_311)))
  
  

```


### Full forecast for top 3 models
```{r}
#Plot model + observed data

#Train and forecast with full data set
ARIMA_38_full <- auto.arima(ts_load_full, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_full, 
                                          K=c(3,8))
                             )

ARIMA_38_full_forecast <- forecast(ARIMA_38_full,
                           xreg=fourier(ts_load_train,
                                        K=c(3,8),
                                        h=31),
                           h=31
                           ) 

ARIMA_38_data<- data.frame(
  date = seq(as.Date("2011-07-01"), length.out = 31, by = "day"),
  value = ARIMA_38_full_forecast$mean
)

write_csv(ARIMA_38_data, 'ARIMA_38.csv')
```


## ETS
```{r}
#Fit and forecast STL + ETS model to data
ETS_train1 <-  stlf(ts_load_train,h=31)

#Plot foresting results
autoplot(ETS_train1) + ylab("Load")

#Plot model + observed data
autoplot(ts_load_full) +
  autolayer(ETS_train1, series="STL + ETS",PI=FALSE) +
  ylab("Load")

ETS_train_scores<- accuracy(ETS_train1$mean,ts_load_full)  

ETS_fit1<- stlf(ts_load_full,h=31)
ETS_output1<- data.frame(
  date = seq(as.Date("2011-07-01"), length.out = 31, by = "day"),
  value = ETS_fit1$mean
)

write_csv(ETS_output1, 'Submissions/ETS1.csv')
```

```

